version: '3.7'

services:
  webui:
    build:
      context: ./webui
    ports:
      - 4200:4200
    environment:
      - PROXY_PORT=8080
      - PROXY_HOST=server
    container_name: webui
    depends_on:
      - server
    links:
      - server
  server:
    build:
      context: ./server
    expose:
      - 8080
    environment:
      - CLIENT_PORT=4200
      - REDIS_URL=redis://redis:6379/4
    container_name: nestjs-server
    depends_on:
      - redis
  redis:
    image: 'bitnami/redis:latest'
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: redis
